ECHO OFF
ECHO		      AMAZON DEMO INSTALLATION INSTRUCTIONS
ECHO  +----------------------------------------------------------------------
ECHO  +
ECHO  +  1.  Go to the hard disk...		  Type:  C:  [Enter]
ECHO  +
ECHO  +  2.  Go to the root directory...	  Type:  CD\ [Enter]
ECHO  +
ECHO  +  3.  Create the Amazon Demo directory...  Type:  MD AMDEMO [Enter]
ECHO  +
ECHO  +  4.  Go to the Amazon Demo directory...   Type:  CD AMDEMO [Enter]
ECHO  +
ECHO  +  5.  Copy all files from the floppy to the hard disk...
ECHO  +
ECHO  + 	      Type:    COPY A:*.*   [Enter]	 for the A: floppy
ECHO  + 	 or
ECHO  + 	      Type:    COPY B:*.*   [Enter]	 for the B: floppy
ECHO  +
ECHO  +  6.  Run the Amazon Demo...		  Type:  AMAZON [Enter]
ECHO  +
ECHO ON
