
;
;Big Red Modem Interface
;

DEVICE      GENERIC 14.4 MODEM
INITSTRING  AT &F &C1 &D2 &Q5 &K0 S46=0
HANGSTRING  AT Z H0
DIALSTRING  ATDT
BAUD        14400
PORT        3
LINE SPEED  19200
TELEPHONE   
NAME        
