;
;Miles Design Audio Interface Library V3.02 of 18-Jan-95
;

DEVICE      Creative Labs AWE-32(TM) General MIDI
DRIVER      SBAWE32.MDI
IO_ADDR     -1
IRQ         -1
DMA_8_BIT   -1
DMA_16_BIT  -1
