# Config file for Dosbox-0.74
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=overlay
mapperfile=mapper.map
[dosbox]
machine=svga_s3
memsize=63
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=3000
[mixer]
[midi]
[sblaster]
[gus]
[speaker]
[joystick]
[serial]
[dos]
[ipx]
