;
; Config file for WHIPLASH
;

Language=English
SourcePath=C:\TEST
DestinationPath=C:\WHIPLASH
Installation=Standard
SoundCard=0xe001
SoundPort=0x220
SoundIRQ=5
SoundDMA=1
MusicCard=0xa009
MusicPort=0x388
