;Fatal Racing sound/music allocation

119				;number of samples
9				;number of GM files
8				;number of tracks




;samples
	ENGINE
	ENGINE2
	BIGCRASH
	SKID1
	GO
	GRSHIFT
	EXPLO
	FENDER
	FENDER2
	LANDSKID
	LIGHTLAN
	BANK
	WALL1
	ROOF
	FATALITY
	KEEPGO
	FINAL1
	FINAL2
	FINAL3
	YEAHHAH
	AAARG
	GOTONE
	WINNER
	HARDER
	RUBBISH
	POOR
	REVERSE
	BLOWTIME
	ESTART
	FALSE
	RACEOVER
	YEAHLOOP
	YEAHCORK
	LOOPCOME
	CORKCOME
	TOOSLOW
	TOOFAST
	RECORD
	SMASH
	BEST
	FAST
	MENDING
	FIXED
	2LEFT
	1LEFT
	0LEFT
	PITIN
	HURTME
	HURTYOU
	ENGINES
	DRIVERS
	LAPPED
	UNLAPPED
	2LAPS
	3LAPS
	4LAPS
	5LAPS
	WIN
	BLOCK
	SLOW
	BASH
	WIN2
	BLOCK2
	SLOW2
	BASH2
	REJECT1
	REJECT2
	TGONE
	TDAMAGE
	REVERST
	TPITS
	ARIEL
	DESILVA
	PULSE
	GLOBAL
	MILLION
	MISSION
	ZIZIN
	REISE
	BRP
	UP
	BOING
	BLOP
	BUTTON
	CARIN
	CAROUT
	TRACK
	START
	WHIPLASH
	1RACE
	2RACE
	3RACE
	4RACE
	5RACE
	6RACE
	7RACE
	8RACE
	ONE
	TWO
	THREE
	FOUR
	FIVE
	SIX
	SEVEN
	EIGHT
	NINE
	TEN
	ELEVEN
	TWELVE
	THIRTEEN
	FOURTEEN
	FIFTEEN
	SIXTEEN
	FATLOTS
	WON
	STAT
	NEWLAP
	NEWFAST
	CONGRAT
	
;music
	INGAME1				;0		General MIDI music
	INGAME2				;1
	INGAME3				;2
	INGAME4				;3
	TITLE				;4		TITLE = INTRO SEQUENCE
	OPTIONS				;5		OPTIONS = SELECTION SCREENS
	LEADBORD			;6
	WINTWO				;7
	WINONE				;8

;General MIDI		CD track

	0		5		;track 1
	1		6		;track 2
	2		7		;track 3
	3		8		;track 4
	0		5		;track 5
	1		6		;track 6
	2		7		;track 7
	3		8		;track 8

	4		2		;intro
	5		4		;options
	6		3		;leaderboard
	7		13		;win2
	8		12		;win1
